export const colorPatterns: Record<string, RegExp> = {
    hex: /#([a-fA-F0-9]{3}|[a-fA-F0-9]{6})\b/,
    rgb: /rgb\((\s*\d{1,3}\s*,\s*){2}\d{1,3}\s*\)/i,
    rgba: /rgba\((\s*\d{1,3}\s*,\s*){3}(0|1|0?\.\d+)\s*\)/i,
    hsl: /hsl\(\s*\d{1,3}\s*,\s*\d{1,3}%\s*,\s*\d{1,3}%\s*\)/i,
    hsla: /hsla\(\s*\d{1,3}\s*,\s*\d{1,3}%\s*,\s*\d{1,3}%\s*,\s*(0|1|0?\.\d+)\s*\)/i,
    namedColors:
        /\b(light(?:\s*|-)?golden(?:\s*|-)?rod(?:\s*|-)?yellow|corn(?:\s*|-)?flower(?:\s*|-)?blue|dark(?:\s*|-)?golden(?:\s*|-)?rod|dark(?:\s*|-)?olive(?:\s*|-)?green|dark(?:\s*|-)?sea(?:\s*|-)?green|medium(?:\s*|-)?sea(?:\s*|-)?green|dark(?:\s*|-)?slate(?:\s*|-)?gray|dark(?:\s*|-)?slate(?:\s*|-)?grey|light(?:\s*|-)?slate(?:\s*|-)?gray|light(?:\s*|-)?slate(?:\s*|-)?grey|light(?:\s*|-)?steel(?:\s*|-)?blue|medium(?:\s*|-)?aqua(?:\s*|-)?marine|medium(?:\s*|-)?spring(?:\s*|-)?green|medium(?:\s*|-)?slate(?:\s*|-)?blue|medium(?:\s*|-)?violet(?:\s*|-)?red|pale(?:\s*|-)?golden(?:\s*|-)?rod|pale(?:\s*|-)?violet(?:\s*|-)?red|light(?:\s*|-)?sky(?:\s*|-)?blue|deep(?:\s*|-)?sky(?:\s*|-)?blue|blue(?:\s*|-)?violet|dark(?:\s*|-)?slate(?:\s*|-)?blue|dodger(?:\s*|-)?blue|fire(?:\s*|-)?brick|floral(?:\s*|-)?white|forest(?:\s*|-)?green|ghost(?:\s*|-)?white|golden(?:\s*|-)?rod|green(?:\s*|-)?yellow|hot(?:\s*|-)?pink|indian(?:\s*|-)?red|lavender(?:\s*|-)?blush|lemon(?:\s*|-)?chiffon|light(?:\s*|-)?golden(?:\s*|-)?rod(?:\s*|-)?yellow|light(?:\s*|-)?sea(?:\s*|-)?green|light(?:\s*|-)?green|light(?:\s*|-)?yellow|light(?:\s*|-)?salmon|light(?:\s*|-)?pink|light(?:\s*|-)?blue|light(?:\s*|-)?cyan|light(?:\s*|-)?coral|dark(?:\s*|-)?khaki|dark(?:\s*|-)?orange|dark(?:\s*|-)?orchid|dark(?:\s*|-)?red|dark(?:\s*|-)?salmon|dark(?:\s*|-)?turquoise|dark(?:\s*|-)?violet|dim(?:\s*|-)?gray|dim(?:\s*|-)?grey|medium(?:\s*|-)?orchid|medium(?:\s*|-)?purple|medium(?:\s*|-)?blue|mint(?:\s*|-)?cream|misty(?:\s*|-)?rose|navajo(?:\s*|-)?white|orange(?:\s*|-)?red|papaya(?:\s*|-)?whip|peach(?:\s*|-)?puff|powder(?:\s*|-)?blue|rebecca(?:\s*|-)?purple|rosy(?:\s*|-)?brown|royal(?:\s*|-)?blue|saddle(?:\s*|-)?brown|sandy(?:\s*|-)?brown|sea(?:\s*|-)?green|sea(?:\s*|-)?shell|spring(?:\s*|-)?green|steel(?:\s*|-)?blue|white(?:\s*|-)?smoke|yellow(?:\s*|-)?green|alice(?:\s*|-)?blue|antique(?:\s*|-)?white|blanched(?:\s*|-)?almond|dark(?:\s*|-)?magenta|burly(?:\s*|-)?wood|cadet(?:\s*|-)?blue|chartreuse|corn(?:\s*|-)?silk|dark(?:\s*|-)?blue|dark(?:\s*|-)?cyan|dark(?:\s*|-)?gray|dark(?:\s*|-)?grey|light(?:\s*|-)?gray|light(?:\s*|-)?grey|dark(?:\s*|-)?green|deep(?:\s*|-)?pink|gainsboro|honeydew|indigo|lawn(?:\s*|-)?green|lime(?:\s*|-)?green|medium(?:\s*|-)?turquoise|midnight(?:\s*|-)?blue|old(?:\s*|-)?lace|olive(?:\s*|-)?drab|pale(?:\s*|-)?green|pale(?:\s*|-)?turquoise|sky(?:\s*|-)?blue|slate(?:\s*|-)?blue|slate(?:\s*|-)?gray|slate(?:\s*|-)?grey|azure|beige|bisque|black|blue|brown|chocolate|coral|crimson|cyan|fuchsia|gray|green|grey|ivory|khaki|lavender|linen|magenta|maroon|moccasin|navy|olive|orange|orchid|peru|pink|plum|purple|red|salmon|sienna|silver|snow|tan|teal|thistle|tomato|turquoise|violet|wheat|white|yellow|gold|lime|aqua)\b/i,
};
